In [1]:
# for code formatter

# pip install black
# pip install nb_black

%load_ext lab_black

In [2]:
import numpy as np

# Numpy Random Module

In [5]:
# generate array in given range

a = np.arange(10) + 5  # indexing
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [87]:
# if we want that the elements in random are generated in the same order then we can apply seed

np.random.seed(1)

In [88]:
# shuffle the elements of an array
np.random.shuffle(a)
print(a)

[6 9 6]


In [15]:
# array of random numbers
a = np.random.rand(2, 3)
print(a)

[[0.75467492 0.28372459 0.11082061]
 [0.1142992  0.04840652 0.77559757]]


In [14]:
# returns values from standard normal distribution
a = np.random.randn(2, 3)
print(a)

[[-0.23393703  2.16256583 -1.0416869 ]
 [ 1.22035869 -1.5125051  -2.20745018]]


In [74]:
# pick three random elements in range [5,10)
a = np.random.randint(5, 10, 3)
print(a)

[6 6 9]


In [86]:
# randomly pick one element from the array
element = np.random.choice([1, 2, 4, 23, 34, 352, 3, 2])
print(element)

4
