In [1]:
# for code formatter

# pip install black
# pip install nb_black

%load_ext lab_black

In [2]:
import numpy as np

# Statistical Computation
- min,max
- mean
- median
- average
- variance
- standard deviation

In [3]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [4]:
# min element
print(np.min(a))

# min element along the axis (multidimensional )
print(np.min(a, axis=0))

print(np.min(a, axis=1))

1
[1 2 3 4]
[1 5]


In [5]:
# mean or average of the all elements
b = np.array([1, 2, 3, 4, 5])

m = sum(b) / len(b)
print(m)

print(np.mean(b))
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

3.0
3.0
[3. 4. 5. 6.]
[2.5 6.5]


In [6]:
# MEDIAN
print(a)
print(np.median(a))

[[1 2 3 4]
 [5 6 7 8]]
4.5


In [7]:
# MEAN VS AVERAGE
c = np.array([1, 5, 4, 2, 0])

print(np.mean(c))

# average is weighted
wts = np.array([1, 2, 3, 4, 5])
print(np.average(c, weights=wts))

2.4
2.066666666666667


In [8]:
# STANDARD DEVIATION (sigma)
# sd = root(summation(sqare of (x-xi)) divide by N)

# own func
mean = np.mean(c)
mystd = np.sqrt(np.mean(abs(c - mean) ** 2))
print(mystd)


# inbuilt function
print(np.std(c))

1.854723699099141
1.854723699099141


In [9]:
# VARIANCE

print(mystd ** 2)

print(np.var(c))

3.440000000000001
3.4400000000000004
