# Working With Numpy  
    


In [1]:
# for code formatter

# pip install black
# pip install nb_black

%load_ext lab_black

In [2]:
import numpy as np

In [3]:
# Arrays in numpy
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

# dimensions of the array
print(arr.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# 2D array
b = np.array([[1], [2], [3], [4]])

print(b)

print(b.shape)
print(len(b.shape))  # tells the dimensions of the array

[[1]
 [2]
 [3]
 [4]]
(4, 1)
2


In [5]:
c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)
print(c.shape)
print(f"elem at 0,2 is {c[0][2]}")

[[1 2 3]
 [4 5 6]]
(2, 3)
elem at 0,2 is 3


### Create zero , ones array and custom


In [6]:
a = np.zeros((3, 3))
print(a)

b = np.ones((3, 4))
print(b)

c = np.full((2, 3), 7)
print(c)

# identity matrix
d = np.eye(5)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7 7]
 [7 7 7]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### Random Matrix

In [7]:
randomMatrix = np.random.random((2, 3))
print(randomMatrix)

[[0.6855105  0.04510773 0.6079378 ]
 [0.85364323 0.85186574 0.96472767]]


In [8]:
# printing the 1st index column
print(randomMatrix[:, 1])

[0.04510773 0.85186574]


In [9]:
randomMatrix[1, 1:3] = 1
print(randomMatrix)

[[0.6855105  0.04510773 0.6079378 ]
 [0.85364323 1.         1.        ]]


### Data Types

In [10]:
z = np.zeros((3, 3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
print(z.dtype)

float64


In [12]:
z = np.zeros((3, 3), dtype=np.int64)
print(z.dtype)

int64


### Mathematical Operations

In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [14]:
# element wise addition
print(x + y)
print(np.add(x, y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [15]:
# element wise subtraction
print(x - y)
print(np.subtract(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]


In [16]:
# element wise product
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [17]:
# element wise division
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
# element wise sqare root
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [19]:
# Matrix Multiplication / Dot Product
print(x)
print(y)

print(x.dot(y))
print(np.dot(x, y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [20]:
# multiplication(dot product) of vectors
# dot product will give scalar

a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])

print(np.dot(a, b))

30


In [21]:
# Sum Function
print(sum(a))

10


In [22]:
# Np sum function
print(x)

# sum along the columns
print(np.sum(x, axis=0))

# sum along the rows
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [23]:
#  Stack Function
print(a)

b = b ** 2
print(b)

# combinig two arrays
a = np.stack((a, b), axis=0)
print(a)

[1 2 3 4]
[ 1  4  9 16]
[[ 1  2  3  4]
 [ 1  4  9 16]]


In [24]:
# Reshape a Numpy array
print(a)

a = a.reshape((2, 4))
print(a)

# automatically figures out (-1)
a = a.reshape((4, -1))
print(a)

[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2  3  4]
 [ 1  4  9 16]]
[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
